### ISSUE TITLE
Wrong C# command in generated code

### ISSUE THREAD

**Issue by jam987** [Skinz3/Antlr.CSharpTool#1]
First of all thanks for this tool. It's working great and makes things much more easy!
As I am not sure which sources you use for the antlr jar file (a link would be useful) I'll open the issue here:

When using the c++ grammer from the antlr repo it produces a mistake in the C# code: it generates ```string.compareTo()``` while it should be with a uppercase letter ```string.CompareTo()```.

**Comment by Skinz3** [comment]
Hello, 
The error you are talking about is not related to the script. (I dont call string.CompareTo()) 

The ANTLR jar is here : https://github.com/Skinz3/Antlr.CSharpTool/blob/master/antlr4-csharp-4.6.6-complete.jar

You can find te 4.6.6 version sources on the official antlr git rep
